import { Project } from "../types/default-type";

export const projects:Project[] = [
  {
    id: 1,
    title: "Portfolio Website",
    description: "A sleek and modern portfolio website showcasing skills and projects.",
    image: "/project/portfolio.jpg",
    category: "Web",
    live: "#",
    github: "#",
  },
  {
    id: 2,
    title: "Logo Design",
    description: "A creative and minimalistic logo designed for a startup.",
    image: "/project/logo.jpg",
    category: "Graphics",
    live: "#",
    github: "",
  },
  {
    id: 3,
    title: "3D Game Prototype",
    description: "A physics-based 3D game prototype built with Godot Engine.",
    image: "/project/game.jpg",
    category: "Game",
    live: "#",
    github: "#",
  },
  {
    id: 4,
    title: "E-Commerce App",
    description: "A mobile-first e-commerce app for seamless online shopping.",
    image: "/project/ecommerce.jpg",
    category: "Web",
    live: "#",
    github: "#",
  },
  {
    id: 5,
    title: "Product Advertisement",
    description: "A high-quality promotional video for a product launch.",
    image: "/project/video.jpg",
    category: "Video",
    live: "#",
    github: "",
  },
  {
    id: 6,
    title: "Creative Branding",
    description: "A unique branding project that enhanced brand identity.",
    image: "/project/branding.jpg",
    category: "Graphics",
    live: "#",
    github: "#",
  },
  {
    id: 7,
    title: "Modern UI/UX Design",
    description: "A clean and user-friendly interface for a mobile app.",
    image: "/project/uiux.jpg",
    category: "Graphics",
    live: "#",
    github: "#",
  },
  {
    id: 8,
    title: "Game Concept Art",
    description: "Illustrated concept art for a new adventure game.",
    image: "/project/concept-art.jpg",
    category: "Game",
    live: "#",
    github: "#",
  },
  {
    id: 9,
    title: "Tech Conference Promo Video",
    description: "A dynamic promotional video for a tech conference.",
    image: "/project/conference-video.jpg",
    category: "Video",
    live: "#",
    github: "",
  },
];

export const projectWithRating:Project[] = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "A fully customizable e-commerce platform with advanced features.",
    image: "/project/ecommerce.jpg",
    category: "Web Development",
    rating: 5,
  },
  {
    id: 3,
    title: "CMS for Education",
    description: "A custom CMS for managing online courses and student data.",
    image: "/project/student-cms.jpg",
    category: "CMS Development",
    rating: 5,
  },
  {
    id: 4,
    title: "Corporate Website",
    description: "A modern and responsive website for a global corporation.",
    image: "/project/global-corporation.jpg",
    category: "Web Development",
    rating: 4,
  },
];